print("Hallo ik ben Brayden wie ben jij")
naam = input("Wat is jouw naam? ")
print("Hallo " + naam + " leuk om jouw te ontmoeten")
print("Ik ben 16 jaar oud")
age = input("Hoe oud ben jij? ")
print("Aha, je bent dus " + age + " jaar oud, leuk zeg!" )
woonplaats = input("Waar woon je? ")
print("oh dus je woont in " + woonplaats )
print("Hallo " + naam + " dus als ik het goed heb woon je in " + woonplaats + " en ben je " + age + " jaar oud")